// pipeline
// {
//     agent any
//     stages
//     {
//         stage("build")
//         {
//             steps
//             {
//                 echo "building the application..."

//                 script
//                 {
//                     def test = 2 + 2 > 3 ? "cool" : "not cool"
//                     echo test
//                 }
//             }
//         }

//         stage("test")
//         {
//             steps
//             {
//                 echo "testing the application..."
//             }
//         }

//         stage("deploy")
//         {
//             steps 
//             {
//                 echo "deploying the application..."
//             }
//         }
//     }
// }


pipeline
{
    agent any
    stages
    {
        stage("run frontend")
        {
            steps
            {
                echo "executing yarn..."
                nodejs('NodeJS 22.8.0')
                {
                    sh 'yarn --version'
                }
            }
        }

        stage("run backend")
        {
            steps
            {
                echo "executing gradle..."
                // withGradle()
                // {
                //     sh './gradlew -v'
                // }
                nodejs("NodeJS 22.8.0")
                {
                    sh 'yarn --version'
                }
            }
        }
    }
}
